version: "3"

services:
  api:
    build:
      context: .
    ports:
      - 8000:8000
    networks:
      - sql-net
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: "sae"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sql-net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - sql-net
volumes:
  db-data:

networks:
  sql-net:
